package com.example.ui

import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.data.CarbonDatabase
import com.example.data.CarbonRepository
import com.example.data.GeminiService
import com.example.data.LoggedAction
import com.example.data.TrackedDay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

/**
 * CarbonViewModel serves as the central state engine for EcoPrint AI.
 * It manages state propagation, reactive stream combinations, preference caching,
 * Room database persistence operations, and triggers external Gemini LLM interactions.
 *
 * @param application The Android Application context.
 * @property repository Carbon database repository helper.
 */
@OptIn(ExperimentalCoroutinesApi::class)
public class CarbonViewModel(
    application: Application,
    private val repository: CarbonRepository = CarbonRepository(CarbonDatabase.getDatabase(application).carbonDao())
) : AndroidViewModel(application) {

    private val prefs = application.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private val _userName = MutableStateFlow(prefs.getString(PREF_USER_NAME, DEFAULT_USER_NAME) ?: DEFAULT_USER_NAME)
    
    /**
     * Observable stream representing the customized username.
     */
    public val userName: StateFlow<String> = _userName.asStateFlow()

    private val _dailyBudget = MutableStateFlow(prefs.getFloat(PREF_DAILY_BUDGET, DEFAULT_DAILY_BUDGET))
    
    /**
     * Observable stream representing the daily carbon budget allowance in kg CO2.
     */
    public val dailyBudget: StateFlow<Float> = _dailyBudget.asStateFlow()

    /**
     * Updates the username and daily carbon budget parameters across state streams and Shared Preferences.
     *
     * @param name The customized username.
     * @param budget The target daily carbon allowance in kg CO2.
     */
    public fun updateUserProfile(name: String, budget: Float): Unit {
        _userName.value = name
        _dailyBudget.value = budget
        prefs.edit()
            .putString(PREF_USER_NAME, name)
            .putFloat(PREF_DAILY_BUDGET, budget)
            .apply()
    }

    private val _selectedDate = MutableStateFlow(getCurrentDateString())
    
    /**
     * Observable stream of the currently selected day formatted as "yyyy-MM-dd".
     */
    public val selectedDate: StateFlow<String> = _selectedDate.asStateFlow()

    private val _isToday = MutableStateFlow(true)
    
    /**
     * Observable state checking if the currently navigated day matches the computer's calendar day.
     */
    public val isToday: StateFlow<Boolean> = _isToday.asStateFlow()

    // Screen input states managed reactively
    private val _carKm = MutableStateFlow(0f)
    private val _flightHoursYearly = MutableStateFlow(0f)
    private val _transitKm = MutableStateFlow(0f)
    private val _electricityKwh = MutableStateFlow(0f)
    private val _heatingLevel = MutableStateFlow("None") // "None", "Low", "Medium", "High"
    private val _dietPreference = MutableStateFlow("Not Set") // "Not Set", "Vegan", "Vegetarian", "Balanced", "Meat Heavy"
    private val _trashBags = MutableStateFlow(0f)
    private val _recycledChecked = MutableStateFlow(false)

    // AI recommendation states
    private val _aiInsight = MutableStateFlow("")
    
    /**
     * Custom environment recommendations text generated by Gemini.
     */
    public val aiInsight: StateFlow<String> = _aiInsight.asStateFlow()

    private val _isLoadingInsight = MutableStateFlow(false)
    
    /**
     * Reflects the current API feedback request state (loading trigger).
     */
    public val isLoadingInsight: StateFlow<Boolean> = _isLoadingInsight.asStateFlow()

    // Reactively load TrackedDay from DB when date changes
    private val _savedDayState = _selectedDate.flatMapLatest { date ->
        repository.getTrackedDay(date)
    }

    /**
     * Reactively load logged carbon actions list when navigated date shifts.
     */
    public val loggedActions: StateFlow<List<LoggedAction>> = _selectedDate.flatMapLatest { date ->
        repository.getLoggedActionsForDate(date)
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    /**
     * Historical tracked record of carbon days list.
     */
    public val historicalDays: StateFlow<List<TrackedDay>> = repository.getAllTrackedDays()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    /**
     * Reactive consecutive tracking counter checking calendar items backwards from today/yesterday.
     */
    public val trackingStreak: StateFlow<Int> = historicalDays.map { days ->
        val sorted = days.distinctBy { it.date }.sortedByDescending { it.date }
        if (sorted.isEmpty()) return@map 0
        
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        var streak = 0
        val cal = Calendar.getInstance()
        cal.time = Date() // Today
        
        var checkingToday = true
        while (true) {
            val formattedDate = sdf.format(cal.time)
            val dayExists = sorted.any { it.date == formattedDate }
            
            if (dayExists) {
                streak++
                cal.add(Calendar.DATE, -1)
                checkingToday = false
            } else {
                if (checkingToday) {
                    cal.add(Calendar.DATE, -1)
                    val formattedYesterday = sdf.format(cal.time)
                    val yesterdayExists = sorted.any { it.date == formattedYesterday }
                    if (yesterdayExists) {
                        streak++
                        cal.add(Calendar.DATE, -1)
                        checkingToday = false
                        continue
                    }
                }
                break
            }
        }
        streak
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), 0)

    /**
     * Combined comprehensive reactive state that collects all atomic flow parameters
     * inside the calculator panel and emits CarbonUiState updates securely.
     */
    public val uiState: StateFlow<CarbonUiState> = combine(
        _selectedDate,
        _carKm,
        _flightHoursYearly,
        _transitKm,
        _electricityKwh,
        _heatingLevel,
        _dietPreference,
        _trashBags,
        _recycledChecked,
        _savedDayState,
        loggedActions
    ) { flows ->
        val date = flows[0] as String
        val car = flows[1] as Float
        val flight = flows[2] as Float
        val transit = flows[3] as Float
        val elec = flows[4] as Float
        val heating = flows[5] as String
        val diet = flows[6] as String
        val trash = flows[7] as Float
        val recycled = flows[8] as Boolean
        val savedDay = flows[9] as? TrackedDay
        @Suppress("UNCHECKED_CAST")
        val actions = flows[10] as List<LoggedAction>
        
        // Co2 carbon conversions using exact factors
        val travelCo2 = computeTransportCo2(car, flight, transit)
        val utilityCo2 = computeUtilityCo2(elec, heating)
        val dietCo2 = computeDietCo2(diet)
        val wasteCo2 = computeWasteCo2(trash, recycled)
        val baseFootprint = travelCo2 + utilityCo2 + dietCo2 + wasteCo2
        
        val offset = actions.sumOf { it.co2Saved.toDouble() }.toFloat()
        val net = (baseFootprint - offset).coerceAtLeast(0f)

        CarbonUiState(
            selectedDate = date,
            carKm = car,
            flightHoursYearly = flight,
            transitKm = transit,
            electricityKwh = elec,
            heatingLevel = heating,
            dietPreference = diet,
            trashBags = trash,
            recycledChecked = recycled,
            transportCo2 = travelCo2,
            utilityCo2 = utilityCo2,
            dietCo2 = dietCo2,
            wasteCo2 = wasteCo2,
            totalFootprint = baseFootprint,
            totalOffset = offset,
            netFootprint = net,
            hasSavedRecord = savedDay != null
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = CarbonUiState(getCurrentDateString())
    )

    init {
        // Automatically synchronize parameters and hydrate screen fields whenever the navigated date shifts
        viewModelScope.launch {
            _selectedDate.collect { date ->
                _isToday.value = (date == getCurrentDateString())
                loadDayFromDatabase(date)
            }
        }
    }

    private fun getCurrentDateString(): String {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        return sdf.format(Date())
    }

    private suspend fun loadDayFromDatabase(date: String): Unit {
        try {
            val saved = repository.getTrackedDay(date).first()
            if (saved != null) {
                _carKm.value = saved.carKm
                _flightHoursYearly.value = saved.flightHours
                _transitKm.value = saved.transitKm
                _electricityKwh.value = saved.elecKwh
                _heatingLevel.value = saved.heatingLevel
                _dietPreference.value = saved.dietChoice
                _trashBags.value = saved.trashBags
                _recycledChecked.value = saved.recycled
            } else {
                // Reset defaults for a fresh, unlogged day
                _carKm.value = 0f
                _flightHoursYearly.value = 0f
                _transitKm.value = 0f
                _electricityKwh.value = 0f
                _heatingLevel.value = "None"
                _dietPreference.value = "Not Set"
                _trashBags.value = 0f
                _recycledChecked.value = false
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    private var saveJob: kotlinx.coroutines.Job? = null

    private fun saveCurrentDayWithDebounce(): Unit {
        saveJob?.cancel()
        saveJob = viewModelScope.launch {
            kotlinx.coroutines.delay(DEBOUNCE_DELAY_MS)
            saveCurrentDayDirectly()
        }
    }

    private suspend fun saveCurrentDayDirectly(): Unit {
        val state = uiState.value
        val trackedDay = TrackedDay(
            date = state.selectedDate,
            transportCo2 = state.transportCo2,
            utilityCo2 = state.utilityCo2,
            dietCo2 = state.dietCo2,
            wasteCo2 = state.wasteCo2,
            totalCo2 = state.totalFootprint,
            carKm = state.carKm,
            flightHours = state.flightHoursYearly,
            transitKm = state.transitKm,
            elecKwh = state.electricityKwh,
            heatingLevel = state.heatingLevel,
            dietChoice = state.dietPreference,
            trashBags = state.trashBags,
            recycled = state.recycledChecked
        )
        repository.insertTrackedDay(trackedDay)
    }

    /**
     * Updates recorded car distance and schedules persistence database write.
     */
    public fun updateCarKm(km: Float): Unit {
        _carKm.value = km
    }

    /**
     * Updates yearly transport flight hours and schedules persistence database write.
     */
    public fun updateFlightHours(hours: Float): Unit {
        _flightHoursYearly.value = hours
    }

    /**
     * Updates public transit distance and schedules persistence database write.
     */
    public fun updateTransitKm(km: Float): Unit {
        _transitKm.value = km
    }

    /**
     * Updates electricity consumption parameters and schedules persistence database write.
     */
    public fun updateElectricityKwh(kwh: Float): Unit {
        _electricityKwh.value = kwh
    }

    /**
     * Updates heating level profile and saves the Day's record.
     */
    public fun updateHeatingLevel(level: String): Unit {
        _heatingLevel.value = level
        saveCurrentDay()
    }

    /**
     * Updates daily dietary option preference and saves active state database tracking.
     */
    public fun updateDietPreference(diet: String): Unit {
        _dietPreference.value = diet
        saveCurrentDay()
    }

    /**
     * Updates trash disposal bag load and triggers immediate local database write.
     */
    public fun updateTrashBags(bags: Float): Unit {
        _trashBags.value = bags
        saveCurrentDay()
    }

    /**
     * Updates eco-friendly recycling checking option.
     */
    public fun updateRecycled(checked: Boolean): Unit {
        _recycledChecked.value = checked
        saveCurrentDay()
    }

    /**
     * Triggers active local SQL data persistence with built-in UI debounce scheduler protection.
     */
    public fun saveCurrentDay(): Unit {
        saveCurrentDayWithDebounce()
    }

    /**
     * Copies inputs from yesterday to populate the selected today's metrics rapidly.
     */
    public fun copyYesterdayInputs(): Unit {
        viewModelScope.launch {
            try {
                val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
                val currentDate = sdf.parse(_selectedDate.value) ?: return@launch
                val cal = Calendar.getInstance()
                cal.time = currentDate
                cal.add(Calendar.DATE, -1)
                val yesterdayStr = sdf.format(cal.time)
                
                val yesterdayData = repository.getTrackedDay(yesterdayStr).first()
                if (yesterdayData != null) {
                    _carKm.value = yesterdayData.carKm
                    _flightHoursYearly.value = yesterdayData.flightHours
                    _transitKm.value = yesterdayData.transitKm
                    _electricityKwh.value = yesterdayData.elecKwh
                    _heatingLevel.value = yesterdayData.heatingLevel
                    _dietPreference.value = yesterdayData.dietChoice
                    _trashBags.value = yesterdayData.trashBags
                    _recycledChecked.value = yesterdayData.recycled
                    
                    // Save today's cloned data
                    saveCurrentDayDirectly()
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }

    /**
     * Increments or decrements selected day navigation boundary.
     * Prevents future calendar navigation.
     *
     * @param days Positive or negative relative day shifts.
     */
    public fun changeDateByDays(days: Int): Unit {
        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        try {
            val date = sdf.parse(_selectedDate.value) ?: Date()
            val cal = Calendar.getInstance()
            cal.time = date
            cal.add(Calendar.DATE, days)
            
            val todayString = getCurrentDateString()
            val targetString = sdf.format(cal.time)
            
            if (days < 0 || targetString <= todayString) {
                _selectedDate.value = targetString
                _aiInsight.value = "" // clear cache to promote fresh recommendation study on navigates
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    /**
     * Inserts an organic eco habit reduction/offset action entry inside Room.
     *
     * @param actionName The exact wording of the habit.
     * @param co2Saved Emissions reduction potential in kilograms of CO2.
     * @param category Environmental focus group categories.
     */
    public fun logHabit(actionName: String, co2Saved: Float, category: String): Unit {
        viewModelScope.launch {
            val action = LoggedAction(
                date = _selectedDate.value,
                actionName = actionName,
                co2Saved = co2Saved,
                category = category
            )
            repository.logAction(action)
        }
    }

    /**
     * Removes an eco action reduced log record by SQL direct primary key identification index.
     *
     * @param id DB LoggedAction auto-incremental long ID index.
     */
    public fun deleteHabit(id: Long): Unit {
        viewModelScope.launch {
            repository.deleteLoggedAction(id)
        }
    }

    /**
     * Contacts active Gemini model with current carbon metrics data frame to draw natural language insights.
     */
    public fun generateAIInsights(): Unit {
        val currentState = uiState.value
        val actions = loggedActions.value
        _isLoadingInsight.value = true
        _aiInsight.value = ""

        viewModelScope.launch {
            val fieldsMap = mapOf(
                KEY_INSIGHT_TRANSPORT to currentState.transportCo2,
                KEY_INSIGHT_UTILITY to currentState.utilityCo2,
                KEY_INSIGHT_DIET to currentState.dietCo2,
                KEY_INSIGHT_WASTE to currentState.wasteCo2
            )
            val insight = GeminiService.getPersonalizedEcoInsights(
                totalCo2 = currentState.totalFootprint,
                fields = fieldsMap,
                loggedActions = actions
            )
            _aiInsight.value = insight
            _isLoadingInsight.value = false
        }
    }

    private fun computeTransportCo2(carKm: Float, flightHoursYearly: Float, transitKm: Float): Float {
        return (carKm * FACTOR_CAR_KM) + (flightHoursYearly * FACTOR_FLIGHT_YEARLY_DAILY) + (transitKm * FACTOR_TRANSIT_KM)
    }

    private fun computeUtilityCo2(electricityKwh: Float, heatingLevel: String): Float {
        val heatingOffset = when (heatingLevel) {
            "None" -> CO2_HEATING_NONE
            "Low" -> CO2_HEATING_LOW
            "Medium" -> CO2_HEATING_MEDIUM
            "High" -> CO2_HEATING_HIGH
            else -> CO2_HEATING_UNKNOWN
        }
        return (electricityKwh * FACTOR_ELEC_KWH) + heatingOffset
    }

    private fun computeDietCo2(preference: String): Float {
        return when (preference) {
            "Not Set" -> CO2_DIET_NOT_SET
            "Vegan" -> CO2_DIET_VEGAN
            "Vegetarian" -> CO2_DIET_VEGETARIAN
            "Balanced" -> CO2_DIET_BALANCED
            "Meat Heavy" -> CO2_DIET_MEAT_HEAVY
            else -> CO2_DIET_UNKNOWN
        }
    }

    private fun computeWasteCo2(trashBags: Float, recycledChecked: Boolean): Float {
        val base = trashBags * FACTOR_TRASH_BAG
        return if (recycledChecked) base * FACTOR_RECYCLING_DISCOUNT else base
    }

    private fun Float.toCarKm(): Float = this / FACTOR_CAR_KM
    private fun Float.toElecKwh(): Float = this / FACTOR_ELEC_KWH

    public companion object {
        private const val PREFS_NAME = "eco_print_prefs"
        private const val PREF_USER_NAME = "user_name"
        private const val PREF_DAILY_BUDGET = "daily_budget"
        private const val DEFAULT_USER_NAME = "Roshan Varma"
        private const val DEFAULT_DAILY_BUDGET = 12.0f
        private const val DEBOUNCE_DELAY_MS = 350L

        // Carbon Factor Coefficients (EMISSIONS FACTOR ALGORITHMS)
        private const val FACTOR_CAR_KM = 0.20f
        private const val FACTOR_FLIGHT_YEARLY_DAILY = 250f / 365f
        private const val FACTOR_TRANSIT_KM = 0.08f
        private const val FACTOR_ELEC_KWH = 0.45f
        private const val FACTOR_TRASH_BAG = 1.5f
        private const val FACTOR_RECYCLING_DISCOUNT = 0.5f

        // Heating carbon thresholds
        private const val CO2_HEATING_NONE = 0f
        private const val CO2_HEATING_LOW = 1.5f
        private const val CO2_HEATING_MEDIUM = 3.5f
        private const val CO2_HEATING_HIGH = 7.0f
        private const val CO2_HEATING_UNKNOWN = 3.5f

        // Diet carbon preference footprints
        private const val CO2_DIET_NOT_SET = 0.0f
        private const val CO2_DIET_VEGAN = 0.8f
        private const val CO2_DIET_VEGETARIAN = 1.4f
        private const val CO2_DIET_BALANCED = 2.2f
        private const val CO2_DIET_MEAT_HEAVY = 3.3f
        private const val CO2_DIET_UNKNOWN = 0.0f

        // Map Keys
        private const val KEY_INSIGHT_TRANSPORT = "Transport Emissions"
        private const val KEY_INSIGHT_UTILITY = "Utility Emissions"
        private const val KEY_INSIGHT_DIET = "Diet Emissions"
        private const val KEY_INSIGHT_WASTE = "Waste Emissions"
    }
}

/**
 * Represent UI values for the single-page Carbon dashboard layout.
 */
public data class CarbonUiState(
    val selectedDate: String,
    val carKm: Float = 0f,
    val flightHoursYearly: Float = 0f,
    val transitKm: Float = 0f,
    val electricityKwh: Float = 0f,
    val heatingLevel: String = "None",
    val dietPreference: String = "Not Set",
    val trashBags: Float = 0f,
    val recycledChecked: Boolean = false,
    
    // Footprint stats calculated metrics (kg CO2)
    val transportCo2: Float = 0f,
    val utilityCo2: Float = 0f,
    val dietCo2: Float = 0f,
    val wasteCo2: Float = 0f,
    
    val totalFootprint: Float = 0f,
    val totalOffset: Float = 0f,
    val netFootprint: Float = 0f,
    val hasSavedRecord: Boolean = false
)

/**
 * Factory class for safely instantiating the CarbonViewModel.
 */
public class CarbonViewModelFactory(private val application: Application) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(CarbonViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return CarbonViewModel(application) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
